add env and changed logging and put it in order
yaroslavvasilenko/memestore pull request #3
Opened 2022-10-26 16:40 UTC by yaroslavvasilenko

2022-10-26 16:46 UTC, silverCase commented on cmd/main.go
> +	a, err := app.NewApp(cfg)
Name variables so people can easily read code.
e.g. a -> app

2022-10-26 16:49 UTC, silverCase commented on cmd/main.go
> +	log.Info("Running Application")
Make logging message more concrete: 
"Running Application" -> "Update Channel created"/"Bot polling started" etc

2022-10-26 16:50 UTC, silverCase commented on cmd/main.go
> +				log.Info(m)
Rework logging of these messages like in line 27.

2022-10-26 16:51 UTC, silverCase commented on cmd/main.go
> +	//a.Run(ctx)
What is this?
If this is here for convenience - leave a comment why it is there and for what purpose

2022-10-26 16:53 UTC, silverCase commented on internal/app/app.go
> +		return nil, err
codestyle
remove redundant tab

2022-10-26 16:53 UTC, silverCase commented on internal/app/app.go
> +		return nil, err
codestyle
remove redundant tab

2022-10-26 16:54 UTC, silverCase commented on internal/app/app.go
> +		LogFile:  logF}, err
codestyle
change positions of arguments: `LogFile:  logF}, err` is very confusing, `{` and `}` should not blend with arguments

2022-10-26 17:07 UTC, silverCase commented on pkg/config/config.go
> +// Simple helper function to read an environment or return a default value
to read an environment variable*

2022-10-26 17:13 UTC, silverCase requested changes
fix all comments

2022-10-27 13:54 UTC, yaroslavvasilenko commented on cmd/main.go
> +	a, err := app.NewApp(cfg)
done

2022-10-27 13:56 UTC, yaroslavvasilenko commented on cmd/main.go
> +				log.Info(m)
Done

2022-10-27 13:57 UTC, yaroslavvasilenko commented on cmd/main.go
> +	//a.Run(ctx)
this is future. I deleted

2022-10-27 13:57 UTC, yaroslavvasilenko commented on internal/app/app.go
> +		return nil, err
No

2022-10-27 14:03 UTC, yaroslavvasilenko commented on internal/app/app.go
> +		LogFile:  logF}, err
Ok

2022-10-27 15:02 UTC, merged